/*
 * This source file was generated by the Gradle 'init' task
 */
package github.user.activity.cli;

import github.user.activity.cli.service.UserActivityService;

public class App {

    public static void main(String[] args) throws Exception {
        System.out.println("Hi dude!");
        UserActivityService userActivityService = new UserActivityService();
        userActivityService.getActivity();
    }
}
